Added comments (Preps for defensive programing)

diff --git a/bin/brew-auto-update b/bin/brew-auto-update
--- a/bin/brew-auto-update
+++ b/bin/brew-auto-update
@@ -1,15 +1,26 @@
 #!/bin/bash
-
-set -eu
+#
+# == Make the script fail fast
+# - Any error
+# - Any unbound variables
+# - SubShell failed
+set -e
+set -u
 set -o pipefail
 
+
+# == Define some variables
+#
 PATH=/usr/local/bin:$PATH
 
 NOTIFICATION_GROUP='com.straxhaber.BrewAutoUpdate'
 NOTIFICATION_SOUND='Glass'
 NOTIFICATION_TITLE='Homebrew'
 
-# Check OS X system settings. Note Homebrew terminology is different from OS X:
+
+# == Check OS X system settings.
+#
+# Note Homebrew terminology is different from OS X:
 #
 # Homebrew: update -> fetch    -> upgrade
 # OS X:     check  -> download -> update
@@ -18,6 +29,9 @@ auto_update=${HOMEBREW_AUTO_UPDATE:-$(defaults read /Library/Preferences/com.app
 auto_fetch=${HOMEBREW_AUTO_FETCH:-$(defaults read /Library/Preferences/com.apple.SoftwareUpdate AutomaticDownload)}
 auto_upgrade=${HOMEBREW_AUTO_UPGRADE:-$(defaults read /Library/Preferences/com.apple.commerce AutoUpdate)}
 
+
+# == Sanity and runtime checks
+#
 # Don't run if auto-update is disabled
 if [ "$auto_update" != 1 ]; then
   exit
@@ -35,6 +49,9 @@ for termapp in iTerm Terminal; do
   fi
 done
 
+
+# == Functions
+#
 function show_notification () {
   notification_subtitle="$1"
   notification_message="$2"
@@ -48,6 +65,9 @@ function show_notification () {
     >/dev/null
 }
 
+
+# == Script section
+#
 # Run brew update and notify user if it failed
 if ! out=$(brew update 2>&1); then
   show_notification 'update failed' "$out"
